### ISSUE TITLE
MissingXMLTags result not correct when check the slice with  'omitempty'

### ISSUE THREAD

**Issue by sunsun314** [clbanning/checkxml#2]
I have a test case like below
```
func TestMissingXMLTagsRecursive(t *testing.T) {

	type test2 struct {
		Name string   `xml:"name,attr"`
		May  []*test2 `xml:"child,omitempty"`
	}
	type test struct {
		May []*test2 `xml:"child"`
	}

	tv := test{}
	data := []byte(`
    <doc>
		<child name="xx">
           <child name="yy">
             <child name="zz">
             </child>
           </child>
           <child name="yz"/>
        </child>
	</doc>`)

	mems, _, err := MissingXMLTags(data, tv)
	fmt.Println(mems)
	if err != nil {
		t.Fatalf(err.Error())
	}
	if len(mems) != 0 {
		t.Fatalf(fmt.Sprintf("missing mems: %d - %#v", len(mems), mems))
	}
}
```
The MissingXMLTags result is    
[child.child.child.childtest2 child.child.childtest2]  

It seams like the 'omitempty' did not work for the slice in object   
I check the code and try to fix it with a null check,But I'm not sure my fix is  correct  
(https://github.com/sunsun314/checkxml/commit/376e5c85027781543bb530f93f966846509ce9c1 It may cause other problem?I tested it with simple cases,it works fine)

**Comment by clbanning** [comment]
MissingXMLTags does not appear to handle recursive struct definitions.  I'll look into this when I have some time.  For now, I've added a BUG notice to the MissingXMLTags documentation.
